---
- name: deploy spot instances
  hosts: localhost
  gather_facts: false
  vars_files:
    - config/config.yml
  roles:
    - ec2

- name: configure instances
  hosts: backend
  tags:
    - configure
    - common
  roles:
    - common
