---
- name: deploy spot instances
  hosts: localhost
  gather_facts: false
  vars_files:
    - config/config.yml
  roles:
    - ec2

- name: baseline instances
  hosts: backend
  become: yes
  vars:
    docker_install_compose: false
    pip_install_packages:
      - name: docker
      - name: docker-compose
  tags:
    - configure
    - common
  roles:
    - common
    - geerlingguy.docker


- name: deploy containers
  hosts: backend
  become: yes
  vars:
    compose_project: elasticsearch-compose.yml
  tags:
    - elasticsearch
  roles:
    - elasticsearch-docker
